version: '3.7'
services:

  server:
    build:
      context: /root/h-platform-automation-cc-server
    image: hpa-cc-server:v0.3
    restart: always
    ports:
      - 8080:8080
    environment:
      - JAEGER_AGENT_HOST=tracing-stack
    volumes:
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
      - /root/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /opt/terraform_0.13.2:/opt/terraform_0.13.2
      - /root/h-platform-automation-core/tf-owncloud:/root/h-platform-automation-core/tf-owncloud
      - /root/h-platform-automation-core/tf-owncloud-docker:/root/h-platform-automation-core/tf-owncloud-docker
